create extension if not exists pgcrypto;

create table if not exists public.committees (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  chair_token text not null unique,
  name text not null,
  topic text not null,
  phase text not null default 'formal_debate',
  status_note text,
  current_speaker_country text,
  created_by uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.committee_memberships (
  id uuid primary key default gen_random_uuid(),
  committee_id uuid not null references public.committees(id) on delete cascade,
  user_id uuid not null,
  role text not null check (role in ('chair', 'delegate')),
  country text,
  display_name text,
  is_active boolean not null default true,
  joined_at timestamptz not null default now(),
  unique (committee_id, user_id)
);

create unique index if not exists committee_delegate_country_unique
on public.committee_memberships (committee_id, lower(country))
where role = 'delegate' and is_active and country is not null;

create table if not exists public.speaker_requests (
  id uuid primary key default gen_random_uuid(),
  committee_id uuid not null references public.committees(id) on delete cascade,
  membership_id uuid not null references public.committee_memberships(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'dismissed', 'completed')),
  requested_at timestamptz not null default now(),
  reviewed_at timestamptz,
  completed_at timestamptz
);

create unique index if not exists speaker_request_pending_unique
on public.speaker_requests (committee_id, membership_id)
where status = 'pending';

create table if not exists public.speaker_queue (
  id uuid primary key default gen_random_uuid(),
  committee_id uuid not null references public.committees(id) on delete cascade,
  membership_id uuid not null references public.committee_memberships(id) on delete cascade,
  country text not null,
  order_index integer not null,
  status text not null default 'queued' check (status in ('queued', 'current', 'completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists speaker_queue_order_unique
on public.speaker_queue (committee_id, order_index);

create unique index if not exists speaker_queue_active_membership_unique
on public.speaker_queue (committee_id, membership_id)
where status in ('queued', 'current');

create table if not exists public.votes (
  id uuid primary key default gen_random_uuid(),
  committee_id uuid not null references public.committees(id) on delete cascade,
  title text not null,
  description text,
  motion_type text not null default 'substantive',
  threshold text not null default 'simple_majority',
  status text not null default 'open' check (status in ('open', 'closed')),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  opened_by uuid not null
);

create table if not exists public.vote_ballots (
  id uuid primary key default gen_random_uuid(),
  vote_id uuid not null references public.votes(id) on delete cascade,
  committee_id uuid not null references public.committees(id) on delete cascade,
  membership_id uuid not null references public.committee_memberships(id) on delete cascade,
  choice text not null check (choice in ('yes', 'no', 'abstain')),
  cast_at timestamptz not null default now(),
  unique (vote_id, membership_id)
);

create table if not exists public.drafts (
  id uuid primary key default gen_random_uuid(),
  committee_id uuid not null references public.committees(id) on delete cascade,
  title text not null,
  description text,
  status text not null default 'open' check (status in ('open', 'closed')),
  created_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists public.draft_signatories (
  id uuid primary key default gen_random_uuid(),
  draft_id uuid not null references public.drafts(id) on delete cascade,
  committee_id uuid not null references public.committees(id) on delete cascade,
  membership_id uuid not null references public.committee_memberships(id) on delete cascade,
  signed_at timestamptz not null default now(),
  unique (draft_id, membership_id)
);

create table if not exists public.event_log (
  id bigint generated by default as identity primary key,
  committee_id uuid not null references public.committees(id) on delete cascade,
  actor_role text not null,
  actor_label text not null,
  kind text not null,
  summary text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_committees_updated_at on public.committees;
create trigger set_committees_updated_at
before update on public.committees
for each row
execute function public.touch_updated_at();

drop trigger if exists set_speaker_queue_updated_at on public.speaker_queue;
create trigger set_speaker_queue_updated_at
before update on public.speaker_queue
for each row
execute function public.touch_updated_at();

create or replace function public.is_committee_member(target_committee_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.committee_memberships
    where committee_id = target_committee_id
      and user_id = auth.uid()
      and is_active
  );
$$;

create or replace function public.is_committee_chair(target_committee_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.committee_memberships
    where committee_id = target_committee_id
      and user_id = auth.uid()
      and role = 'chair'
      and is_active
  );
$$;

create or replace function public.append_event_log(
  p_committee_id uuid,
  p_actor_role text,
  p_actor_label text,
  p_kind text,
  p_summary text,
  p_detail jsonb default '{}'::jsonb
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.event_log (
    committee_id,
    actor_role,
    actor_label,
    kind,
    summary,
    detail
  )
  values (
    p_committee_id,
    p_actor_role,
    p_actor_label,
    p_kind,
    p_summary,
    coalesce(p_detail, '{}'::jsonb)
  );
$$;

create or replace function public.generate_committee_code()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate text;
begin
  loop
    candidate := 'MUN-' || upper(substr(encode(gen_random_bytes(3), 'hex'), 1, 4));
    exit when not exists (
      select 1 from public.committees where code = candidate
    );
  end loop;

  return candidate;
end;
$$;

create or replace function public.lookup_committee(p_code text)
returns table (
  committee_id uuid,
  code text,
  name text,
  topic text,
  phase text,
  status_note text,
  delegate_count bigint,
  claimed_countries text[]
)
language sql
stable
security definer
set search_path = public
as $$
  select
    c.id as committee_id,
    c.code,
    c.name,
    c.topic,
    c.phase,
    c.status_note,
    count(m.id) filter (where m.role = 'delegate' and m.is_active) as delegate_count,
    coalesce(
      array_agg(m.country order by m.country)
        filter (where m.role = 'delegate' and m.is_active and m.country is not null),
      '{}'::text[]
    ) as claimed_countries
  from public.committees c
  left join public.committee_memberships m
    on m.committee_id = c.id
  where c.code = upper(trim(p_code))
  group by c.id, c.code, c.name, c.topic, c.phase, c.status_note;
$$;

create or replace function public.get_my_membership(p_code text)
returns table (
  membership_id uuid,
  committee_id uuid,
  role text,
  country text,
  display_name text,
  joined_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    m.id as membership_id,
    m.committee_id,
    m.role,
    m.country,
    m.display_name,
    m.joined_at
  from public.committee_memberships m
  join public.committees c
    on c.id = m.committee_id
  where c.code = upper(trim(p_code))
    and m.user_id = auth.uid()
    and m.is_active
  limit 1;
$$;

create or replace function public.create_committee(p_name text, p_topic text)
returns table (
  committee_id uuid,
  code text,
  chair_token text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_committee_id uuid;
  v_code text;
  v_chair_token text;
begin
  if v_user_id is null then
    raise exception 'Anonymous session required before creating a committee.';
  end if;

  if nullif(trim(p_name), '') is null or nullif(trim(p_topic), '') is null then
    raise exception 'Committee name and topic are required.';
  end if;

  v_code := public.generate_committee_code();
  v_chair_token := encode(gen_random_bytes(16), 'hex');

  insert into public.committees (
    code,
    chair_token,
    name,
    topic,
    created_by
  )
  values (
    v_code,
    v_chair_token,
    trim(p_name),
    trim(p_topic),
    v_user_id
  )
  returning id into v_committee_id;

  insert into public.committee_memberships (
    committee_id,
    user_id,
    role,
    display_name
  )
  values (
    v_committee_id,
    v_user_id,
    'chair',
    'Chair'
  );

  perform public.append_event_log(
    v_committee_id,
    'chair',
    'Chair',
    'committee_created',
    format('Committee "%s" created.', trim(p_name)),
    jsonb_build_object('topic', trim(p_topic))
  );

  return query
  select v_committee_id, v_code, v_chair_token;
end;
$$;

create or replace function public.claim_chair_access(p_code text, p_chair_token text)
returns table (
  committee_id uuid
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_committee public.committees%rowtype;
  v_existing public.committee_memberships%rowtype;
begin
  if v_user_id is null then
    raise exception 'Anonymous session required before chair access can be claimed.';
  end if;

  select *
  into v_committee
  from public.committees
  where code = upper(trim(p_code))
    and chair_token = p_chair_token;

  if not found then
    raise exception 'Invalid chair link.';
  end if;

  select *
  into v_existing
  from public.committee_memberships
  where committee_id = v_committee.id
    and user_id = v_user_id
    and is_active;

  if found then
    if v_existing.role = 'delegate' then
      raise exception 'This browser is already joined as a delegate for this committee.';
    end if;
  end if;

  if not found then
    insert into public.committee_memberships (
      committee_id,
      user_id,
      role,
      display_name
    )
    values (
      v_committee.id,
      v_user_id,
      'chair',
      'Chair'
    );

    perform public.append_event_log(
      v_committee.id,
      'chair',
      'Chair',
      'chair_rejoined',
      'Chair accessed the control room.',
      '{}'::jsonb
    );
  end if;

  return query
  select v_committee.id;
end;
$$;

create or replace function public.claim_delegate_slot(
  p_code text,
  p_country text,
  p_display_name text default null
)
returns table (
  membership_id uuid,
  committee_id uuid
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_committee public.committees%rowtype;
  v_existing public.committee_memberships%rowtype;
  v_membership_id uuid;
begin
  if v_user_id is null then
    raise exception 'Anonymous session required before joining a committee.';
  end if;

  if nullif(trim(p_country), '') is null then
    raise exception 'Choose a country before joining.';
  end if;

  select *
  into v_committee
  from public.committees
  where code = upper(trim(p_code));

  if not found then
    raise exception 'Committee not found.';
  end if;

  select *
  into v_existing
  from public.committee_memberships
  where committee_id = v_committee.id
    and user_id = v_user_id
    and is_active;

  if found then
    if v_existing.role = 'chair' then
      raise exception 'This browser is already the chair for this committee.';
    end if;

    if v_existing.role = 'delegate' then
      return query
      select v_existing.id, v_existing.committee_id;
      return;
    end if;
  end if;

  if exists (
    select 1
    from public.committee_memberships
    where committee_id = v_committee.id
      and role = 'delegate'
      and is_active
      and lower(country) = lower(trim(p_country))
  ) then
    raise exception 'That country has already been claimed.';
  end if;

  insert into public.committee_memberships (
    committee_id,
    user_id,
    role,
    country,
    display_name
  )
  values (
    v_committee.id,
    v_user_id,
    'delegate',
    trim(p_country),
    nullif(trim(p_display_name), '')
  )
  returning id into v_membership_id;

  perform public.append_event_log(
    v_committee.id,
    'delegate',
    trim(p_country),
    'delegate_joined',
    format('%s joined the committee.', trim(p_country)),
    jsonb_build_object('display_name', nullif(trim(p_display_name), ''))
  );

  return query
  select v_membership_id, v_committee.id;
end;
$$;

create or replace function public.raise_placard(p_code text)
returns table (
  request_id uuid
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_membership public.committee_memberships%rowtype;
  v_request_id uuid;
begin
  select m.*
  into v_membership
  from public.committee_memberships m
  join public.committees c
    on c.id = m.committee_id
  where c.code = upper(trim(p_code))
    and m.user_id = auth.uid()
    and m.role = 'delegate'
    and m.is_active;

  if not found then
    raise exception 'Join the committee as a delegate before raising placard.';
  end if;

  if exists (
    select 1
    from public.speaker_requests
    where committee_id = v_membership.committee_id
      and membership_id = v_membership.id
      and status = 'pending'
  ) then
    raise exception 'You already have a pending placard request.';
  end if;

  if exists (
    select 1
    from public.speaker_queue
    where committee_id = v_membership.committee_id
      and membership_id = v_membership.id
      and status in ('queued', 'current')
  ) then
    raise exception 'You are already on the speakers list.';
  end if;

  insert into public.speaker_requests (
    committee_id,
    membership_id
  )
  values (
    v_membership.committee_id,
    v_membership.id
  )
  returning id into v_request_id;

  perform public.append_event_log(
    v_membership.committee_id,
    'delegate',
    v_membership.country,
    'placard_raised',
    format('%s raised placard.', v_membership.country),
    '{}'::jsonb
  );

  return query
  select v_request_id;
end;
$$;

create or replace function public.queue_speaker_request(p_code text, p_request_id uuid)
returns table (
  queue_id uuid
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_committee public.committees%rowtype;
  v_request public.speaker_requests%rowtype;
  v_membership public.committee_memberships%rowtype;
  v_next_order integer;
  v_queue_id uuid;
begin
  select c.*
  into v_committee
  from public.committees c
  where c.code = upper(trim(p_code));

  if not found or not public.is_committee_chair(v_committee.id) then
    raise exception 'Chair access required.';
  end if;

  select *
  into v_request
  from public.speaker_requests
  where id = p_request_id
    and committee_id = v_committee.id
    and status = 'pending';

  if not found then
    raise exception 'Pending request not found.';
  end if;

  select *
  into v_membership
  from public.committee_memberships
  where id = v_request.membership_id;

  if exists (
    select 1
    from public.speaker_queue
    where committee_id = v_committee.id
      and membership_id = v_membership.id
      and status in ('queued', 'current')
  ) then
    raise exception 'Delegate is already on the speakers list.';
  end if;

  select coalesce(max(order_index), 0) + 1
  into v_next_order
  from public.speaker_queue
  where committee_id = v_committee.id;

  update public.speaker_requests
  set status = 'accepted',
      reviewed_at = now()
  where id = v_request.id;

  insert into public.speaker_queue (
    committee_id,
    membership_id,
    country,
    order_index,
    status
  )
  values (
    v_committee.id,
    v_membership.id,
    v_membership.country,
    v_next_order,
    'queued'
  )
  returning id into v_queue_id;

  perform public.append_event_log(
    v_committee.id,
    'chair',
    'Chair',
    'speaker_queued',
    format('%s added to the speakers list.', v_membership.country),
    jsonb_build_object('order', v_next_order)
  );

  return query
  select v_queue_id;
end;
$$;

create or replace function public.dismiss_speaker_request(p_code text, p_request_id uuid)
returns table (
  request_id uuid
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_committee public.committees%rowtype;
  v_request public.speaker_requests%rowtype;
  v_membership public.committee_memberships%rowtype;
begin
  select c.*
  into v_committee
  from public.committees c
  where c.code = upper(trim(p_code));

  if not found or not public.is_committee_chair(v_committee.id) then
    raise exception 'Chair access required.';
  end if;

  select *
  into v_request
  from public.speaker_requests
  where id = p_request_id
    and committee_id = v_committee.id
    and status = 'pending';

  if not found then
    raise exception 'Pending request not found.';
  end if;

  select *
  into v_membership
  from public.committee_memberships
  where id = v_request.membership_id;

  update public.speaker_requests
  set status = 'dismissed',
      reviewed_at = now()
  where id = v_request.id;

  perform public.append_event_log(
    v_committee.id,
    'chair',
    'Chair',
    'speaker_request_dismissed',
    format('%s placard request dismissed.', v_membership.country),
    '{}'::jsonb
  );

  return query
  select v_request.id;
end;
$$;

create or replace function public.advance_speaker(p_code text)
returns table (
  queue_id uuid,
  current_speaker_country text,
  queue_status text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_committee public.committees%rowtype;
  v_current public.speaker_queue%rowtype;
  v_next public.speaker_queue%rowtype;
begin
  select c.*
  into v_committee
  from public.committees c
  where c.code = upper(trim(p_code));

  if not found or not public.is_committee_chair(v_committee.id) then
    raise exception 'Chair access required.';
  end if;

  select *
  into v_current
  from public.speaker_queue
  where committee_id = v_committee.id
    and status = 'current'
  order by order_index
  limit 1;

  if found then
    update public.speaker_queue
    set status = 'completed'
    where id = v_current.id;

    update public.speaker_requests
    set status = 'completed',
        completed_at = now()
    where id = (
      select sr.id
      from public.speaker_requests sr
      where sr.committee_id = v_committee.id
        and sr.membership_id = v_current.membership_id
        and sr.status = 'accepted'
      order by sr.requested_at
      limit 1
    );
  end if;

  select *
  into v_next
  from public.speaker_queue
  where committee_id = v_committee.id
    and status = 'queued'
  order by order_index
  limit 1;

  if found then
    update public.speaker_queue
    set status = 'current'
    where id = v_next.id;

    update public.committees
    set current_speaker_country = v_next.country
    where id = v_committee.id;

    perform public.append_event_log(
      v_committee.id,
      'chair',
      'Chair',
      'speaker_advanced',
      case
        when v_current.id is null then format('%s took the floor.', v_next.country)
        else format('Advanced from %s to %s.', v_current.country, v_next.country)
      end,
      jsonb_build_object('current_speaker', v_next.country)
    );

    return query
    select v_next.id, v_next.country, 'current';
  end if;

  update public.committees
  set current_speaker_country = null
  where id = v_committee.id;

  perform public.append_event_log(
    v_committee.id,
    'chair',
    'Chair',
    'speaker_advanced',
    case
      when v_current.id is null then 'Advance requested, but the queue is empty.'
      else format('%s finished and the floor is now empty.', v_current.country)
    end,
    '{}'::jsonb
  );

  return query
  select null::uuid, null::text, 'idle'::text;
end;
$$;

create or replace function public.set_committee_phase(
  p_code text,
  p_phase text,
  p_note text default null
)
returns table (
  committee_id uuid,
  phase text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_committee public.committees%rowtype;
begin
  select c.*
  into v_committee
  from public.committees c
  where c.code = upper(trim(p_code));

  if not found or not public.is_committee_chair(v_committee.id) then
    raise exception 'Chair access required.';
  end if;

  update public.committees
  set phase = p_phase,
      status_note = nullif(trim(p_note), '')
  where id = v_committee.id;

  perform public.append_event_log(
    v_committee.id,
    'chair',
    'Chair',
    'phase_changed',
    format('Committee phase changed to %s.', replace(p_phase, '_', ' ')),
    jsonb_build_object('status_note', nullif(trim(p_note), ''))
  );

  return query
  select v_committee.id, p_phase;
end;
$$;

create or replace function public.open_vote(
  p_code text,
  p_title text,
  p_description text default null,
  p_motion_type text default 'substantive',
  p_threshold text default 'simple_majority'
)
returns table (
  vote_id uuid
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_committee public.committees%rowtype;
  v_vote_id uuid;
begin
  select c.*
  into v_committee
  from public.committees c
  where c.code = upper(trim(p_code));

  if not found or not public.is_committee_chair(v_committee.id) then
    raise exception 'Chair access required.';
  end if;

  if nullif(trim(p_title), '') is null then
    raise exception 'Vote title is required.';
  end if;

  if exists (
    select 1
    from public.votes
    where committee_id = v_committee.id
      and status = 'open'
  ) then
    raise exception 'Close the current vote before opening another one.';
  end if;

  insert into public.votes (
    committee_id,
    title,
    description,
    motion_type,
    threshold,
    status,
    opened_by
  )
  values (
    v_committee.id,
    trim(p_title),
    nullif(trim(p_description), ''),
    p_motion_type,
    p_threshold,
    'open',
    auth.uid()
  )
  returning id into v_vote_id;

  update public.committees
  set phase = 'voting'
  where id = v_committee.id;

  perform public.append_event_log(
    v_committee.id,
    'chair',
    'Chair',
    'vote_opened',
    format('Opened vote on "%s".', trim(p_title)),
    jsonb_build_object(
      'motion_type', p_motion_type,
      'threshold', p_threshold
    )
  );

  return query
  select v_vote_id;
end;
$$;

create or replace function public.cast_vote(p_vote_id uuid, p_choice text)
returns table (
  vote_id uuid,
  choice text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_vote public.votes%rowtype;
  v_membership public.committee_memberships%rowtype;
begin
  select *
  into v_vote
  from public.votes
  where id = p_vote_id
    and status = 'open';

  if not found then
    raise exception 'Vote is closed or unavailable.';
  end if;

  select *
  into v_membership
  from public.committee_memberships
  where committee_id = v_vote.committee_id
    and user_id = auth.uid()
    and role = 'delegate'
    and is_active;

  if not found then
    raise exception 'Delegate access required.';
  end if;

  insert into public.vote_ballots (
    vote_id,
    committee_id,
    membership_id,
    choice
  )
  values (
    v_vote.id,
    v_vote.committee_id,
    v_membership.id,
    p_choice
  )
  on conflict (vote_id, membership_id)
  do update
  set choice = excluded.choice,
      cast_at = now();

  perform public.append_event_log(
    v_vote.committee_id,
    'delegate',
    v_membership.country,
    'vote_cast',
    format('%s updated a ballot.', v_membership.country),
    jsonb_build_object('choice', p_choice)
  );

  return query
  select v_vote.id, p_choice;
end;
$$;

create or replace function public.close_vote(p_code text, p_vote_id uuid)
returns table (
  vote_id uuid,
  yes_count bigint,
  no_count bigint,
  abstain_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_committee public.committees%rowtype;
  v_vote public.votes%rowtype;
  v_yes bigint;
  v_no bigint;
  v_abstain bigint;
begin
  select c.*
  into v_committee
  from public.committees c
  where c.code = upper(trim(p_code));

  if not found or not public.is_committee_chair(v_committee.id) then
    raise exception 'Chair access required.';
  end if;

  select *
  into v_vote
  from public.votes
  where id = p_vote_id
    and committee_id = v_committee.id
    and status = 'open';

  if not found then
    raise exception 'Open vote not found.';
  end if;

  select
    count(*) filter (where choice = 'yes'),
    count(*) filter (where choice = 'no'),
    count(*) filter (where choice = 'abstain')
  into v_yes, v_no, v_abstain
  from public.vote_ballots
  where vote_id = v_vote.id;

  update public.votes
  set status = 'closed',
      closed_at = now()
  where id = v_vote.id;

  update public.committees
  set phase = 'formal_debate'
  where id = v_committee.id;

  perform public.append_event_log(
    v_committee.id,
    'chair',
    'Chair',
    'vote_closed',
    format(
      'Closed vote on "%s" (Yes %s, No %s, Abstain %s).',
      v_vote.title,
      v_yes,
      v_no,
      v_abstain
    ),
    jsonb_build_object(
      'yes', v_yes,
      'no', v_no,
      'abstain', v_abstain
    )
  );

  return query
  select v_vote.id, v_yes, v_no, v_abstain;
end;
$$;

create or replace function public.open_draft(
  p_code text,
  p_title text,
  p_description text default null
)
returns table (
  draft_id uuid
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_committee public.committees%rowtype;
  v_draft_id uuid;
begin
  select c.*
  into v_committee
  from public.committees c
  where c.code = upper(trim(p_code));

  if not found or not public.is_committee_chair(v_committee.id) then
    raise exception 'Chair access required.';
  end if;

  if nullif(trim(p_title), '') is null then
    raise exception 'Draft title is required.';
  end if;

  insert into public.drafts (
    committee_id,
    title,
    description
  )
  values (
    v_committee.id,
    trim(p_title),
    nullif(trim(p_description), '')
  )
  returning id into v_draft_id;

  perform public.append_event_log(
    v_committee.id,
    'chair',
    'Chair',
    'draft_opened',
    format('Opened signatories for "%s".', trim(p_title)),
    '{}'::jsonb
  );

  return query
  select v_draft_id;
end;
$$;

create or replace function public.toggle_draft_signatory(p_draft_id uuid)
returns table (
  draft_id uuid,
  signed boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_draft public.drafts%rowtype;
  v_membership public.committee_memberships%rowtype;
  v_existing public.draft_signatories%rowtype;
begin
  select *
  into v_draft
  from public.drafts
  where id = p_draft_id
    and status = 'open';

  if not found then
    raise exception 'Draft is closed or unavailable.';
  end if;

  select *
  into v_membership
  from public.committee_memberships
  where committee_id = v_draft.committee_id
    and user_id = auth.uid()
    and role = 'delegate'
    and is_active;

  if not found then
    raise exception 'Delegate access required.';
  end if;

  select *
  into v_existing
  from public.draft_signatories
  where draft_id = v_draft.id
    and membership_id = v_membership.id;

  if found then
    delete from public.draft_signatories
    where id = v_existing.id;

    perform public.append_event_log(
      v_draft.committee_id,
      'delegate',
      v_membership.country,
      'draft_signatory_removed',
      format('%s removed support from "%s".', v_membership.country, v_draft.title),
      '{}'::jsonb
    );

    return query
    select v_draft.id, false;
    return;
  end if;

  insert into public.draft_signatories (
    draft_id,
    committee_id,
    membership_id
  )
  values (
    v_draft.id,
    v_draft.committee_id,
    v_membership.id
  );

  perform public.append_event_log(
    v_draft.committee_id,
    'delegate',
    v_membership.country,
    'draft_signatory_added',
    format('%s signed on to "%s".', v_membership.country, v_draft.title),
    '{}'::jsonb
  );

  return query
  select v_draft.id, true;
end;
$$;

create or replace function public.close_draft(p_code text, p_draft_id uuid)
returns table (
  draft_id uuid,
  signatory_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_committee public.committees%rowtype;
  v_draft public.drafts%rowtype;
  v_signatory_count bigint;
begin
  select c.*
  into v_committee
  from public.committees c
  where c.code = upper(trim(p_code));

  if not found or not public.is_committee_chair(v_committee.id) then
    raise exception 'Chair access required.';
  end if;

  select *
  into v_draft
  from public.drafts
  where id = p_draft_id
    and committee_id = v_committee.id
    and status = 'open';

  if not found then
    raise exception 'Open draft not found.';
  end if;

  select count(*)
  into v_signatory_count
  from public.draft_signatories
  where draft_id = v_draft.id;

  update public.drafts
  set status = 'closed',
      closed_at = now()
  where id = v_draft.id;

  perform public.append_event_log(
    v_committee.id,
    'chair',
    'Chair',
    'draft_closed',
    format('Closed "%s" with %s signatories.', v_draft.title, v_signatory_count),
    jsonb_build_object('signatory_count', v_signatory_count)
  );

  return query
  select v_draft.id, v_signatory_count;
end;
$$;

create or replace function public.add_chair_note(p_code text, p_note text)
returns table (
  logged boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_committee public.committees%rowtype;
begin
  select c.*
  into v_committee
  from public.committees c
  where c.code = upper(trim(p_code));

  if not found or not public.is_committee_chair(v_committee.id) then
    raise exception 'Chair access required.';
  end if;

  if nullif(trim(p_note), '') is null then
    raise exception 'Chair note cannot be empty.';
  end if;

  perform public.append_event_log(
    v_committee.id,
    'chair',
    'Chair',
    'chair_note',
    trim(p_note),
    '{}'::jsonb
  );

  return query
  select true;
end;
$$;

alter table public.committees enable row level security;
alter table public.committee_memberships enable row level security;
alter table public.speaker_requests enable row level security;
alter table public.speaker_queue enable row level security;
alter table public.votes enable row level security;
alter table public.vote_ballots enable row level security;
alter table public.drafts enable row level security;
alter table public.draft_signatories enable row level security;
alter table public.event_log enable row level security;

drop policy if exists committee_members_can_read_committees on public.committees;
create policy committee_members_can_read_committees
on public.committees
for select
to authenticated
using (public.is_committee_member(id));

drop policy if exists committee_members_can_read_memberships on public.committee_memberships;
create policy committee_members_can_read_memberships
on public.committee_memberships
for select
to authenticated
using (public.is_committee_member(committee_id));

drop policy if exists committee_members_can_read_requests on public.speaker_requests;
create policy committee_members_can_read_requests
on public.speaker_requests
for select
to authenticated
using (public.is_committee_member(committee_id));

drop policy if exists committee_members_can_read_queue on public.speaker_queue;
create policy committee_members_can_read_queue
on public.speaker_queue
for select
to authenticated
using (public.is_committee_member(committee_id));

drop policy if exists committee_members_can_read_votes on public.votes;
create policy committee_members_can_read_votes
on public.votes
for select
to authenticated
using (public.is_committee_member(committee_id));

drop policy if exists committee_members_can_read_ballots on public.vote_ballots;
create policy committee_members_can_read_ballots
on public.vote_ballots
for select
to authenticated
using (public.is_committee_member(committee_id));

drop policy if exists committee_members_can_read_drafts on public.drafts;
create policy committee_members_can_read_drafts
on public.drafts
for select
to authenticated
using (public.is_committee_member(committee_id));

drop policy if exists committee_members_can_read_signatories on public.draft_signatories;
create policy committee_members_can_read_signatories
on public.draft_signatories
for select
to authenticated
using (public.is_committee_member(committee_id));

drop policy if exists committee_members_can_read_event_log on public.event_log;
create policy committee_members_can_read_event_log
on public.event_log
for select
to authenticated
using (public.is_committee_member(committee_id));

grant select on public.committees to authenticated;
grant select on public.committee_memberships to authenticated;
grant select on public.speaker_requests to authenticated;
grant select on public.speaker_queue to authenticated;
grant select on public.votes to authenticated;
grant select on public.vote_ballots to authenticated;
grant select on public.drafts to authenticated;
grant select on public.draft_signatories to authenticated;
grant select on public.event_log to authenticated;

grant execute on function public.lookup_committee(text) to authenticated;
grant execute on function public.get_my_membership(text) to authenticated;
grant execute on function public.create_committee(text, text) to authenticated;
grant execute on function public.claim_chair_access(text, text) to authenticated;
grant execute on function public.claim_delegate_slot(text, text, text) to authenticated;
grant execute on function public.raise_placard(text) to authenticated;
grant execute on function public.queue_speaker_request(text, uuid) to authenticated;
grant execute on function public.dismiss_speaker_request(text, uuid) to authenticated;
grant execute on function public.advance_speaker(text) to authenticated;
grant execute on function public.set_committee_phase(text, text, text) to authenticated;
grant execute on function public.open_vote(text, text, text, text, text) to authenticated;
grant execute on function public.cast_vote(uuid, text) to authenticated;
grant execute on function public.close_vote(text, uuid) to authenticated;
grant execute on function public.open_draft(text, text, text) to authenticated;
grant execute on function public.toggle_draft_signatory(uuid) to authenticated;
grant execute on function public.close_draft(text, uuid) to authenticated;
grant execute on function public.add_chair_note(text, text) to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'committees'
  ) then
    execute 'alter publication supabase_realtime add table public.committees';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'committee_memberships'
  ) then
    execute 'alter publication supabase_realtime add table public.committee_memberships';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'speaker_requests'
  ) then
    execute 'alter publication supabase_realtime add table public.speaker_requests';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'speaker_queue'
  ) then
    execute 'alter publication supabase_realtime add table public.speaker_queue';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'votes'
  ) then
    execute 'alter publication supabase_realtime add table public.votes';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'vote_ballots'
  ) then
    execute 'alter publication supabase_realtime add table public.vote_ballots';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'drafts'
  ) then
    execute 'alter publication supabase_realtime add table public.drafts';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'draft_signatories'
  ) then
    execute 'alter publication supabase_realtime add table public.draft_signatories';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'event_log'
  ) then
    execute 'alter publication supabase_realtime add table public.event_log';
  end if;
end
$$;
